version: "3"
services:
  # aws local deployment
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3, sqs, kinesis, cloudwatch, dynamo
    ports:
      - "4549-4566:4549-4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./aws:/docker-entrypoint-initaws.d
    command: sh -c "docker-entrypoint-initaws.d/init-service.sh"
    networks:
      - backend

  # postgres set up
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./psqlScripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_NAME=ai_study_tutor
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - PGDATA=/var/lib/postgresql/data/db
    networks:
      - backend

volumes:
  localstack_data: {}

networks:
  backend: {}